database:
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "root"
    dbname: "yunyez"
    sslmode: "disable" # 禁用SSL
    max_idle_conns: 10 # 最大空闲连接数
    max_open_conns: 100 # 最大打开连接数
    conn_max_lifetime: 3600 # 连接最大生命周期，单位秒
    time_zone: "Asia/Shanghai" # 时区设置
    # 模式列表
    schemas:
      - "iot" # 设备
      - "media" # 媒体(音频/图像/视频)
      - "auth" # 用户与账户系统
      - "public" # 公共模式，默认模式
  
  mongo:
    host: "localhost"
    port: 27017
    user: "mongo"
    password: "mongo"
    dbname: "yunyez"
