mqtt:
  address: "tcp://127.0.0.1:1883"
  client:
    username: "root"
    password: "root123"

# 消息转发规则
rule:
  model: "http"

# 订阅主题列表
topics:
  - "+/+/+/voice/server"

# 音频临时存储路径
audio:
  storage: "storage/tmp/audio"
